// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccessibilityController from "./accessibility_controller"
application.register("accessibility", AccessibilityController)
import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)
import BannerController from "./banner_controller"
application.register("banner", BannerController)
import CancelWarningController from "./cancel_warning_controller"
application.register("cancel-warning", CancelWarningController)
import DetailsController from "./details_controller"
application.register("details", DetailsController)
import DSController from "./ds_controller"
application.register("ds", DSController)
import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)
import PrintController from "./print_controller"
application.register("print", PrintController)
import RadioButtonWarningController from "./radio_button_warning_controller"
application.register("radio-button-warning", RadioButtonWarningController)
import ReliefsController from "./reliefs_controller"
application.register("reliefs", ReliefsController)
import SelectController from "./select_controller"
application.register("select", SelectController)
import TimeoutWarningController from "./timeout_warning_controller"
application.register("timeout-warning", TimeoutWarningController)
import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
import InputFilterController from "./input_filter_controller"
application.register("input-filter", InputFilterController)
import CustomSubmitController from "./custom_submit_controller"
application.register("custom-submit", CustomSubmitController)
import UpperTextController from "./upper_text_controller"
application.register("upper-text", UpperTextController)
import CleanUrlController from "./clean_url_controller"
application.register("clean-url", CleanUrlController)