# frozen_string_literal: true

# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'simplecov'
require 'cucumber/rails'
require 'capybara-screenshot/cucumber'

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
# begin
#  DatabaseCleaner.strategy = :transaction
# rescue NameError
#  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
# end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

Capybara::Screenshot.register_filename_prefix_formatter(:cucumber) do |scenario|
  "screenshot_#{scenario.name.tr(' ', '-')}"
end

Capybara.save_path = ENV['CAPYBARA_SAVE_PATH'] unless ENV['CAPYBARA_SAVE_PATH'].nil?

# Keep only the screenshots generated from the last failing test suite
Capybara::Screenshot.prune_strategy = :keep_last_run

Capybara.register_driver :selenium_chrome do |app|
  opts = Selenium::WebDriver::Chrome::Options.new
  opts.add_option('useAutomationExtension', false)
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: opts)
end

# register a remote selenium chrome base driver. The URL for the remote driver selenium hub must be
# set using the environment variable CAPYBARA_REMOTE_URL
Capybara.register_driver :selenium_remote_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(takes_screenshots: true,
                                                                  'chromeOptions' =>
                                                                  { 'args' => ['--ignore-certificate-errors'] })

  Capybara::Selenium::Driver.new(app,
                                 browser: :remote,
                                 url: ENV['CAPYBARA_REMOTE_URL'],
                                 desired_capabilities: capabilities)
end

# register a local selenium firefox based driver, which ignores insecure certificates, and
# has a screen size of 800x800
Capybara.register_driver :selenium_firefox do |app|
  opts = Selenium::WebDriver::Firefox::Options.new(screen_size: [800, 800])
  capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(accept_insecure_certs: true)
  Capybara::Selenium::Driver.new(app, browser: :firefox, options: opts, desired_capabilities: capabilities)
end

# register a remote selenium firefox based driver, which ignores insecure certs
Capybara.register_driver :selenium_remote_firefox do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(accept_insecure_certs: true)
  Capybara::Selenium::Driver.new(app,
                                 browser: :remote,
                                 url: ENV['CAPYBARA_REMOTE_URL'],
                                 desired_capabilities: capabilities)
end

# enable screen shots for our various drivers
Capybara::Screenshot.register_driver(:selenium_chrome) do |driver, path|
  driver.browser.save_screenshot(path)
end
Capybara::Screenshot.register_driver(:selenium_remote_chrome) do |driver, path|
  driver.browser.save_screenshot(path)
end
Capybara::Screenshot.register_driver(:selenium_firefox) do |driver, path|
  driver.browser.save_screenshot(path)
end
Capybara::Screenshot.register_driver(:selenium_remote_firefox) do |driver, path|
  driver.browser.save_screenshot(path)
end

# Set the default and javascript driver from the environment if set
Capybara.default_driver = ENV['CAPYBARA_DRIVER'].to_sym unless ENV['CAPYBARA_DRIVER'].nil?
Capybara.javascript_driver = ENV['CAPYBARA_DRIVER'].to_sym unless ENV['CAPYBARA_DRIVER'].nil?

# override the default wait time as we seem to have network issues
Capybara.default_max_wait_time = 30

# Set the environment variable CAPYBARA_APP_HOST to run the tests against a remote instance
# or local instance of the application, on a local instance, fix the host and port
unless ENV['CAPYBARA_APP_HOST'].nil?
  Capybara.configure do |config|
    config.app_host = ENV['CAPYBARA_APP_HOST']
    config.run_server = ENV['CAPYBARA_RUN_SERVER'] || true
    if config.run_server
      config.server_host = '0.0.0.0'
      config.server_port = 2099
      config.always_include_port = true
    end
  end
end
