version: '3.4'
services:
  ${DOCKERIMAGENAME}-app-${ENVIRONMENT}:
    volumes:
    - /var/log/${VOLUME_PATH}/share/:/var/tmp/share/:z
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - autotest-proxy.env
  ${DOCKERIMAGENAME}-selenium-hub-${ENVIRONMENT}:
    image: lg-bld-cont01.development.local:8443/docker-hub-proxy-cache/selenium/hub:4.21.0-20240522
    container_name: ${DOCKERIMAGENAME}-selenium-hub-${ENVIRONMENT}
    networks:
      - common
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=90
    ports:
      - "${SELHUB_PUBLISH_PORT}:4442"
      - "${SELHUB_SUB_PORT}:4443"
      - "${SELHUB_TEST_PORT}:4444"
  ${DOCKERIMAGENAME}-firefox-${ENVIRONMENT}:
    image: ${REGISTRY}/revscot-firefox:${TAG}
    container_name: ${DOCKERIMAGENAME}-firefox-${ENVIRONMENT}
    shm_size: 2gb
    hostname: firefox
    env_file:
      - autotest-proxy.env
    volumes:
      - /var/log/${VOLUME_PATH}/share/:/var/tmp/share/:z
    depends_on:
      - ${DOCKERIMAGENAME}-selenium-hub-${ENVIRONMENT}
    environment:
      - SE_EVENT_BUS_HOST=${DOCKERIMAGENAME}-selenium-hub-${ENVIRONMENT}
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSION_REQUEST_TIMEOUT=90
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1280
    ports:
      - "${SELFIREFOX_VNC_PORT}:5900"
      - "${SELFIREFOX_NOVNC_PORT}:7900"
    networks:
      - common
  ${DOCKERIMAGENAME}-vnc2flv-${ENVIRONMENT}:
    image: lg-bld-cont01.development.local:8443/docker-hub-proxy-cache/vimagick/vnc2flv
    entrypoint: /bin/sh -c "/bin/sh -c \"$${@}\""
    command:
      - /bin/sh
      - -c
      - |
           sleep 15s
           flvrec.py -P /pwdfile -o record.flv ${DOCKERHOST} ${SELFIREFOX_VNC_PORT}
    container_name: ${DOCKERIMAGENAME}-vnc2flv-${ENVIRONMENT}
    depends_on:
      - ${DOCKERIMAGENAME}-firefox-${ENVIRONMENT}
    volumes:
      - ./vnc-password.txt:/pwdfile:Z
      - /var/log/${VOLUME_PATH}/video/:/data/:Z
    stop_signal: SIGINT
    networks:
      - common
